user_array = [
	"allen-p",
	"arnold-j",
	"arora-h",
	"badeer-r",
	"bass-e",
	"baughman-d",
	"beck-s",
	"benson-r",
	"blair-l",
	"brawner-s",
	"buy-r",
	"campbell-l",
	"carson-m",
	"cash-m",
	"causholli-m",
	"corman-s",
	"crandell-s",
	"cuilla-m",
	"dasovich-j",
	"davis-d",
	"dean-c",
	"delainey-d",
	"derrick-j",
	"dickson-s",
	"donoho-l",
	"donohoe-t",
	"dorland-c",
	"ermis-f",
	"farmer-d",
	"fischer-m",
	"forney-j",
	"fossum-d",
	"gang-l",
	"gay-r",
	"geaccone-t",
	"germany-c",
	"gilbertsmith-d",
	"giron-d",
	"grigsby-m",
	"guzman-m",
	"haedicke-m",
	"hain-m",
	"harris-s",
	"hayslett-r",
	"heard-m",
	"hendrickson-s",
	"hernandez-j",
	"hodge-j",
	"holst-k",
	"horton-s",
	"hyatt-k",
	"hyvl-d",
	"jones-t",
	"kaminski-v",
	"kean-s",
	"keavey-p",
	"keiser-k",
	"king-j",
	"kitchen-l",
	"kuykendall-t",
	"lavorato-j",
	"lay-k",
	"lenhart-m",
	"lewis-a",
	"linder-e",
	"lokay-m",
	"lokey-t",
	"love-p",
	"lucci-p",
	"maggi-m",
	"mann-k",
	"martin-t",
	"may-l",
	"mccarty-d",
	"mcconnell-m",
	"mckay-b",
	"mckay-j",
	"mclaughlin-e",
	"merriss-s",
	"meyers-a",
	"mims-thurston-p",
	"motley-m",
	"neal-s",
	"nemec-g",
	"panus-s",
	"parks-j",
	"pereira-s",
	"perlingiere-d",
	"phanis-s",
	"pimenov-v",
	"platter-p",
	"presto-k",
	"quenet-j",
	"quigley-d",
	"rapp-b",
	"reitmeyer-j",
	"richey-c",
	"ring-a",
	"rodrique-r",
	"rogers-b",
	"ruscitti-k",
	"sager-e",
	"saibi-e",
	"salisbury-h",
	"sanders-r",
	"scholtes-d",
	"schoolcraft-d",
	"schwieger-j",
	"scott-s",
	"semperger-c",
	"shackleton-s",
	"shankman-j",
	"shapiro-r",
	"shively-h",
	"skilling-j",
	"slinger-r",
	"smith-m",
	"solberg-g",
	"south-s",
	"staab-t",
	"stclair-c",
	"steffes-j",
	"stepenovitch-j",
	"stokley-c",
	"storey-g",
	"sturm-f",
	"swerzbin-m",
	"symes-k",
	"taylor-m",
	"tholt-j",
	"thomas-p",
	"townsend-j",
	"tycholiz-b",
	"ward-k",
	"watson-k",
	"weldon-c",
	"whalley-g",
	"whalley-l",
	"white-s",
	"whitt-m",
	"williams-j",
	"williams-w3",
	"wolfe-j",
	"ybarbo-p",
	"zipper-a",
	"zufferli-j"
];

user_email_map = {
	"allen-p": "klen..al@enron.com",
	"arnold-j": "odohnl.jarn@enron.com",
	"arora-h": "oaarrryh.ar@enron.com",
	"badeer-r": "aeerodberrt.b@enron.com",
	"bailey-s": "ieyuslans.ba@enron.com",
	"bass-e": "ebassric.@enron.com",
	"baughman-d": "hanonm.bdaug@enron.com",
	"beck-s": "callyks.be@enron.com",
	"benson-r": "esononberrt.b@enron.com",
	"blair-l": "iynn.rlbla@enron.com",
	"brawner-s": "e..brrfawn@enron.com",
	"buy-r": "rbuyick.@enron.com",
	"campbell-l": "el..clafmpb@enron.com",
	"carson-m": "snikeo.mcar@enron.com",
	"cash-m": ".ashicchemlle@enron.com",
	"causholli-m": "lulionkma.icasho@enron.com",
	"corman-s": "crmanohellsey.@enron.com",
	"crandell-s": "nalledan.scra@enron.com",
	"cuilla-m": "ullaairtimn.c@enron.com",
	"dasovich-j": "oichevff.jdas@enron.com",
	"davis-d": "iana.sddav@enron.com",
	"dean-c": "araignc.de@enron.com",
	"delainey-d": "ny..deewlai@enron.com",
	"derrick-j": "rickarmesj.de@enron.com",
	"dickson-s": "csontkacys.di@enron.com",
	"donoho-l": "nhoinodyl.do@enron.com",
	"donohoe-t": "heom.odtono@enron.com",
	"dorland-c": "randhlrisc.do@enron.com",
	"ermis-f": "msranikf.er@enron.com",
	"farmer-d": "jrmer..fa@enron.com",
	"fischer-m": "cerarhy.mfis@enron.com",
	"forney-j": "mrney..fo@enron.com",
	"fossum-d": "smrewu.dfos@enron.com",
	"gang-l": "lgangisa.@enron.com",
	"gay-r": "ly..ga@enron.com",
	"geaccone-t": "aconecracyt.ge@enron.com",
	"germany-c": "ranyhmrisc.ge@enron.com",
	"gilbertsmith-d": "semithug.dogilbrt-@enron.com",
	"giron-d": "cron..gi@enron.com",
	"griffith-j": "fithofhn.jgri@enron.com",
	"grigsby-m": "gbyikse.mgri@enron.com",
	"guzman-m": "",
	"haedicke-m": "ce..hkaeedi@enron.com",
	"hain-m": "",
	"harris-s": "",
	"hayslett-r": "lttode.hrays@enron.com",
	"heard-m": "adarirem.he@enron.com",
	"hendrickson-s": "kdsonctts.ohenric@enron.com",
	"hernandez-j": "nndezauan.jher@enron.com",
	"hodge-j": "gohn.ejhod@enron.com",
	"holst-k": "lteitshk.ho@enron.com",
	"horton-s": "hrtonotanlsey.@enron.com",
	"hyatt-k": "atevitnk.hy@enron.com",
	"hyvl-d": "dyvlan.h@enron.com",
	"jones-t": "eana.stjon@enron.com",
	"kaminski-v": "k.kamijins@enron.com",
	"kean-s": "jan..ke@enron.com",
	"keavey-p": "aeyetverp.ke@enron.com",
	"keiser-k": "eam.krkeis@enron.com",
	"king-j": "jkingeff.@enron.com",
	"kitchen-l": "ichentouisle.k@enron.com",
	"kuykendall-t": "leloritkuy.knda@enron.com",
	"lavorato-j": "latoavor@enron.com",
	"lay-k": "lyennaekth.@enron.com",
	"lenhart-m": "retattmew.hlnha@enron.com",
	"lewis-a": "hwis..le@enron.com",
	"linder-e": "",
	"lokay-m": ".okaylichemlle@enron.com",
	"lokey-t": "tokeyeb.l@enron.com",
	"love-p": "mve..lo@enron.com",
	"lucci-p": "tcci..lu@enron.com",
	"maggi-m": "gike.immag@enron.com",
	"mann-k": "kannay.m@enron.com",
	"martin-t": "artin..ma@enron.com",
	"may-l": "l.mayarry@enron.com",
	"mccarty-d": "crtyaannyd.mc@enron.com",
	"mcconnell-m": "onellnark.mmcc@enron.com",
	"mckay-b": "arad.ybmck@enron.com",
	"mckay-j": ".ckaymonatjhan@enron.com",
	"mclaughlin-e": "lainrrle.moclugh@enron.com",
	"merriss-s": "",
	"meyers-a": "eerslyberat.m@enron.com",
	"mims-thurston-p": "lms..mi@enron.com",
	"motley-m": "lyatte.mmot@enron.com",
	"neal-s": "acottls.ne@enron.com",
	"nemec-g": "eecermalgd.n@enron.com",
	"panus-s": "u.stepsanihepan@enron.com",
	"parks-j": "jarksoe.p@enron.com",
	"pereira-s": "r..peawrei@enron.com",
	"perlingiere-d": "ilereerad.bpering@enron.com",
	"phanis-s": "u.stepsanihepan@enron.com",
	"pimenov-v": "mnovleadiv.pi@enron.com",
	"platter-p": "elrhilpip.lpatt@enron.com",
	"presto-k": "mesto..pr@enron.com",
	"quenet-j": "eoe.qtjuen@enron.com",
	"quigley-d": "ileyugtchd.qu@enron.com",
	"rapp-b": "brappill.@enron.com",
	"reitmeyer-j": "myeraey.rjeit@enron.com",
	"richey-c": "iheyocopecr.r@enron.com",
	"ring-a": "igndrneaa.r@enron.com",
	"ring-r": "rngiciharrd.@enron.com",
	"rodrique-r": "diguerobinr.ro@enron.com",
	"rogers-b": "rrsenjbmina.oge@enron.com",
	"ruscitti-k": "sitticevink.ru@enron.com",
	"sager-e": "e.rlizebetahsag@enron.com",
	"saibi-e": "bric.iesai@enron.com",
	"salisbury-h": "ulryolehn.dsaisb@enron.com",
	"sanchez-m": "eazonimue.qsnch@enron.com",
	"sanders-r": "r..sasbnde@enron.com",
	"scholtes-d": "hltesoianad.sc@enron.com",
	"schoolcraft-d": "lccrafarretdll.shoo@enron.com",
	"schwieger-j": "igeriem.sjchw@enron.com",
	"scott-s": "otusatns.sc@enron.com",
	"semperger-c": "prgereara.csem@enron.com",
	"shackleton-s": "oknarassha.clet@enron.com",
	"shankman-j": "mn..sahaank@enron.com",
	"shapiro-r": "rhoichrrd.asapi@enron.com",
	"shively-h": "l..shysive@enron.com",
	"skilling-j": "lingelff.jski@enron.com",
	"slinger-r": "neryagn.rsli@enron.com",
	"smith-m": "tatt.hmsmi@enron.com",
	"solberg-g": "brgeier.gsol@enron.com",
	"south-s": "othteuvesn.s@enron.com",
	"staab-t": "saabhteretsa.@enron.com",
	"stclair-c": "araroilc.cl@enron.com",
	"steffes-j": "e..stsdeff@enron.com",
	"stepenovitch-j": "tnchoesjte.peovi@enron.com",
	"stokley-c": "",
	"storey-g": "oeyeorffg.st@enron.com",
	"sturm-f": "jurm..st@enron.com",
	"swerzbin-m": "rbinizke.mswe@enron.com",
	"symes-k": "eate.sksym@enron.com",
	"taylor-m": "tyloraegall <.@enron.com>",
	"tholt-j": "so.adsndre@enron.com",
	"thomas-p": "domas..th@enron.com",
	"townsend-j": "nendusdy.jtow@enron.com",
	"tycholiz-b": "colizharryb.ty@enron.com",
	"ward-k": "kardim.w@enron.com",
	"watson-k": "ownimbkrlye.ats@enron.com",
	"weldon-c": "wldoneharlces.@enron.com",
	"whalley-g": "leyrelg.gwha@enron.com",
	"whalley-l": "leyrelg.gwha@enron.com",
	"white-s": "wite..wh@enron.com",
	"whitt-m": "tark.tmwhi@enron.com",
	"williams-j": "liamslasonj.wi@enron.com",
	"williams-w3": "lamsiill.bwil@enron.com",
	"wolfe-j": "leasofnj.wo@enron.com",
	"ybarbo-p": "aboaurl.py'b@enron.com",
	"zipper-a": "prndye.azip@enron.com",
	"zufferli-j": "frlioehn.jzuf@enron.com",
}
