user_array = [
	"allen-p",
	"arnold-j",
	"arora-h",
	"badeer-r",
	"bass-e",
	"baughman-d",
	"beck-s",
	"benson-r",
	"blair-l",
	"brawner-s",
	"buy-r",
	"campbell-l",
	"carson-m",
	"cash-m",
	"causholli-m",
	"corman-s",
	"crandell-s",
	"cuilla-m",
	"dasovich-j",
	"davis-d",
	"dean-c",
	"delainey-d",
	"derrick-j",
	"dickson-s",
	"donoho-l",
	"donohoe-t",
	"dorland-c",
	"ermis-f",
	"farmer-d",
	"fischer-m",
	"forney-j",
	"fossum-d",
	"gang-l",
	"gay-r",
	"geaccone-t",
	"germany-c",
	"gilbertsmith-d",
	"giron-d",
	"grigsby-m",
	"guzman-m",
	"haedicke-m",
	"hain-m",
	"harris-s",
	"hayslett-r",
	"heard-m",
	"hendrickson-s",
	"hernandez-j",
	"hodge-j",
	"holst-k",
	"horton-s",
	"hyatt-k",
	"hyvl-d",
	"jones-t",
	"kaminski-v",
	"kean-s",
	"keavey-p",
	"keiser-k",
	"king-j",
	"kitchen-l",
	"kuykendall-t",
	"lavorato-j",
	"lay-k",
	"lenhart-m",
	"lewis-a",
	"linder-e",
	"lokay-m",
	"lokey-t",
	"love-p",
	"lucci-p",
	"maggi-m",
	"mann-k",
	"martin-t",
	"may-l",
	"mccarty-d",
	"mcconnell-m",
	"mckay-b",
	"mckay-j",
	"mclaughlin-e",
	"merriss-s",
	"meyers-a",
	"mims-thurston-p",
	"motley-m",
	"neal-s",
	"nemec-g",
	"panus-s",
	"parks-j",
	"pereira-s",
	"perlingiere-d",
	"phanis-s",
	"pimenov-v",
	"platter-p",
	"presto-k",
	"quenet-j",
	"quigley-d",
	"rapp-b",
	"reitmeyer-j",
	"richey-c",
	"ring-a",
	"rodrique-r",
	"rogers-b",
	"ruscitti-k",
	"sager-e",
	"saibi-e",
	"salisbury-h",
	"sanders-r",
	"scholtes-d",
	"schoolcraft-d",
	"schwieger-j",
	"scott-s",
	"semperger-c",
	"shackleton-s",
	"shankman-j",
	"shapiro-r",
	"shively-h",
	"skilling-j",
	"slinger-r",
	"smith-m",
	"solberg-g",
	"south-s",
	"staab-t",
	"stclair-c",
	"steffes-j",
	"stepenovitch-j",
	"stokley-c",
	"storey-g",
	"sturm-f",
	"swerzbin-m",
	"symes-k",
	"taylor-m",
	"tholt-j",
	"thomas-p",
	"townsend-j",
	"tycholiz-b",
	"ward-k",
	"watson-k",
	"weldon-c",
	"whalley-g",
	"whalley-l",
	"white-s",
	"whitt-m",
	"williams-j",
	"williams-w3",
	"wolfe-j",
	"ybarbo-p",
	"zipper-a",
	"zufferli-j"
];

user_email_map = {
	"allen-p": "phillip.allen@enron.com",
	"arnold-j": "john.arnold@enron.com",
	"arora-h": "harry.arora@enron.com",
	"badeer-r": "robert.badeer@enron.com",
	"bass-e": "eric.bass@enron.com",
	"baughman-d": "don.baughman@enron.com",
	"beck-s": "patti.thompson@enron.com",
	"benson-r": "robert.benson@enron.com",
	"blair-l": "lynn.blair@enron.com",
	"brawner-s": "sandra.brawner@enron.com",
	"buy-r": "rick.buy@enron.com",
	"campbell-l": "larry.campbell@enron.com",
	"carson-m": "mike.carson@enron.com",
	"cash-m": "michelle.cash@enron.com",
	"causholli-m": "monika.causholli@enron.com",
	"corman-s": "shelley.corman@enron.com",
	"crandell-s": "sean.crandall@enron.com",
	"cuilla-m": "martin.cuilla@enron.com",
	"dasovich-j": "jeff.dasovich@enron.com",
	"davis-d": "dana.davis@enron.com",
	"dean-c": "clint.dean@enron.com",
	"delainey-d": "david.delainey@enron.com",
	"derrick-j": "james.derrick@enron.com",
	"dickson-s": "stacy.dickson@enron.com",
	"donoho-l": "lindy.donoho@enron.com",
	"donohoe-t": "tom.donohoe@enron.com",
	"dorland-c": "chris.dorland@enron.com",
	"ermis-f": "frank.ermis@enron.com",
	"farmer-d": "daren.farmer@enron.com",
	"fischer-m": "mark.fisher@enron.com",
	"forney-j": "m..forney@enron.com",
	"fossum-d": "drew.fossum@enron.com",
	"gang-l": "lisa.gang@enron.com",
	"gay-r": "rob.gay@enron.com",
	"geaccone-t": "tracy.geaccone@enron.com",
	"germany-c": "chris.germany@enron.com",
	"gilbertsmith-d": "doug.gilbert-smith@enron.com",
	"giron-d": "darron.giron@enron.com",
	"grigsby-m": "mike.grigsby@enron.com",
	"guzman-m": "mark.guzman@enron.com",
	"haedicke-m": "mark.haedicke@enron.com",
	"hain-m": "mary.hain@enron.com",
	"harris-s": "sharris1@enron.com",
	"hayslett-r": "rod.hayslett@enron.com",
	"heard-m": "marie.heard@enron.com",
	"hendrickson-s": "scott.hendrickson@enron.com",
	"hernandez-j": "judy.hernandez@enron.com",
	"hodge-j": "jeffrey.hodge@enron.com",
	"holst-k": "keith.holst@enron.com",
	"horton-s": "stanley.horton@enron.com",
	"hyatt-k": "kevin.hyatt@enron.com",
	"hyvl-d": "dan.hyvl@enron.com",
	"jones-t": "tana.jones@enron.com",
	"kaminski-v": "vince.kaminski@enron.com",
	"kean-s": "steven.kean@enron.com",
	"keavey-p": "peter.keavey@enron.com",
	"keiser-k": "kam.keiser@enron.com",
	"king-j": "jeff.king@enron.com",
	"kitchen-l": "louise.kitchen@enron.com",
	"kuykendall-t": "tori.kuykendall@enron.com",
	"lavorato-j": "lavorato@enron.com",
	"lay-k": "kenneth.lay@enron.com",
	"lenhart-m": "matthew.lenhart@enron.com",
	"lewis-a": "andrew.lewis@enron.com",
	"linder-e": "eric.linder@enron.com",
	"lokay-m": "michelle.lokay@enron.com",
	"lokey-t": "teb.lokey@enron.com",
	"love-p": "phillip.love@enron.com",
	"lucci-p": "t..lucci@enron.com",
	"maggi-m": "mike.maggi@enron.com",
	"mann-k": "kay.mann@enron.com",
	"martin-t": "a..martin@enron.com",
	"may-l": "larry.may@enron.com",
	"mccarty-d": "danny.mccarty@enron.com",
	"mcconnell-m": "mike.mcconnell@enron.com",
	"mckay-b": "brad.mckay@enron.com",
	"mckay-j": "jonathan.mckay@enron.com",
	"mclaughlin-e": "errol.mclaughlin@enron.com",
	"merriss-s": "steven.merris@enron.com",
	"meyers-a": "albert.meyers@enron.com",
	"mims-thurston-p": "l..mims@enron.com",
	"motley-m": "matt.motley@enron.com",
	"neal-s": "scott.neal@enron.com",
	"nemec-g": "gerald.nemec@enron.com",
	"panus-s": "stephanie.panus@enron.com",
	"parks-j": "joe.parks@enron.com",
	"pereira-s": "susan.pereira@enron.com",
	"perlingiere-d": "debra.perlingiere@enron.com",
	"phanis-s": "stephanie.panus@enron.com",
	"pimenov-v": "vladi.pimenov@enron.com",
	"platter-p": "phillip.platter@enron.com",
	"presto-k": "m..presto@enron.com",
	"quenet-j": "joe.quenet@enron.com",
	"quigley-d": "dutch.quigley@enron.com",
	"rapp-b": "bill.rapp@enron.com",
	"reitmeyer-j": "jay.reitmeyer@enron.com",
	"richey-c": "cooper.richey@enron.com",
	"ring-a": "andrea.ring@enron.com",
	"rodrique-r": "robin.rodrigue@enron.com",
	"rogers-b": "benjamin.rogers@enron.com",
	"ruscitti-k": "kevin.ruscitti@enron.com",
	"sager-e": "elizabeth.sager@enron.com",
	"saibi-e": "eric.saibi@enron.com",
	"salisbury-h": "holden.salisbury@enron.com",
	"sanders-r": "richard.sanders@enron.com",
	"scholtes-d": "diana.scholtes@enron.com",
	"schoolcraft-d": "darrell.schoolcraft@enron.com",
	"schwieger-j": "jim.schwieger@enron.com",
	"scott-s": "susan.scott@enron.com",
	"semperger-c": "cara.semperger@enron.com",
	"shackleton-s": "sara.shackleton@enron.com",
	"shankman-j": "jeffrey.shankman@enron.com",
	"shapiro-r": "richard.shapiro@enron.com",
	"shively-h": "hunter.shively@enron.com",
	"skilling-j": "jeff.skilling@enron.com",
	"slinger-r": "ryan.slinger@enron.com",
	"smith-m": "matt.smith@enron.com",
	"solberg-g": "geir.solberg@enron.com",
	"south-s": "steven.south@enron.com",
	"staab-t": "theresa.staab@enron.com",
	"stclair-c": "carol.clair@enron.com",
	"steffes-j": "d..steffes@enron.com",
	"stepenovitch-j": "joe.stepenovitch@enron.com",
	"stokley-c": "chris.stokley@enron.com",
	"storey-g": "geoff.storey@enron.com",
	"sturm-f": "j..sturm@enron.com",
	"swerzbin-m": "mike.swerzbin@enron.com",
	"symes-k": "kate.symes@enron.com",
	"taylor-m": "mark.taylor@enron.com",
	"tholt-j": "jane.tholt@enron.com",
	"thomas-p": "d..thomas@enron.com",
	"townsend-j": "judy.townsend@enron.com",
	"tycholiz-b": "barry.tycholiz@enron.com",
	"ward-k": "kim.ward@enron.com",
	"watson-k": "kimberly.watson@enron.com",
	"weldon-c": "charles.weldon@enron.com",
	"whalley-g": "greg.whalley@enron.com",
	"whalley-l": "greg.whalley@enron.com",
	"white-s": "w..white@enron.com",
	"whitt-m": "mwhitt@enron.com",
	"williams-j": "jason.williams@enron.com",
	"williams-w3": "bill.williams@enron.com",
	"wolfe-j": "jason.wolfe@enron.com",
	"ybarbo-p": "paul.y'barbo@enron.com",
	"zipper-a": "andy.zipper@enron.com",
	"zufferli-j": "john.zufferli@enron.com"
}
